### ISSUE TITLE
Create Onboarding for User Data

### ISSUE THREAD

**Issue by lauhon** [Superlight-Labs/Superlight#23]
## Description

As a User I want to add basic information about myself (username, email) to be able to refer to myself to other users and to verify myself via mail later on.

## Acceptance Criteria

* After hitting the "Get started" Button on the welcome screen, the user gets redirected to a new Onboarding Screen
* The Screen looks as in the [Design](https://www.figma.com/file/K2pP2tStW835VLoOpTnBkD/Superlight-Wireframes---2.Version?node-id=358-118&t=PnQUYv1EmELJAc8X-0)
* Email and Username are required fields, without entering that, the user cannot proceed and the "Next" button is in disabled state
* The back button leads back to the welcome screen

## Rough TODOs
* Rename the existing Components "onboarding.stack.tsx" & "onboarding.screen.tsx" to "setup-wallet.stack.tsx" and "setup-wallet.screen.tsx"
* Create a new component called OnboardingScreen and add it to the Root Stack navigator (in App.tsx)
* Add new fields email and username to the database (in the schema.prisma file)
* Extend the types in the backend to accept mail and username  and update the coresponding code in "useCreateAuth.ts" 

![Onboarding](https://user-images.githubusercontent.com/46261860/233286787-73970164-2e2d-4585-b552-e7cce92a8610.png)

**Comment by vishal7738639800** [comment]
Hey @lauhon, I would like to contribute.
can you please elaborate the problem

**Comment by lauhon** [comment]
Hey @vishal7738639800, thats awesome!

Sorry for the short description, we didn't expect much contributions yet. I will update it so it makes more sense.

Design wise we didnt have anything yet, so I Sketched together a small design for you on Figma - will add that to the description as well

**Comment by lauhon** [comment]
Updated the description to (roughly) contain all relevant information - if you have any questions about how to setup the project feel free to contact me via mail or linkedIn (you can find the information on my [github profile](https://github.com/lauhon)
